baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
title = "blog | alex jackson"
disqusShortname = "blog-zb5zgvwauw"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false
  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "~/blog"
    subtitle = "Alex Jackon's technical(ish) blog. Looking to find a good path toward the future."
    owner = "Alex Jackson"
    keywords = ""
    copyright = "Alex Jackson, 2020"
    menuMore = "show more"
    readMore = "see more"
    readOtherPosts = "Read other posts"
    missingContentMessage = "blog: 1: page: not found :("
    missingBackButtonLabel = "exit back to home page"

    [languages.en.params.logo]
      logoText = "Alex@Jackson:~/blog$"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "projects"
        url = "/projects"
